from enum import Enum, auto


class Token(Enum):
    DEC_NUMBER = auto()
    STRING = auto()
    EQUALITY_OPERATOR = auto()
    BOOLEAN = auto()
    FLOAT_NUMBER = auto()
    COMPARISON_OPERATOR = auto()
    ADDITIVE_OPERATOR = auto()
    NEGATION = auto()
    MULTIPLICATIVE_OPERATOR = auto()
    LET = auto()
    VAR = auto()
    NAME = auto()
    ASSIGNMENT_OPERATOR = auto()
    COMMENT = auto()
    WS = auto()
    NEWLINE = auto()
    RETURN = auto()
    BREAK = auto()
    ELSE = auto()
    ELIF = auto()
    FOR = auto()
    IN = auto()
    WHILE = auto()
    OR = auto()
    AND = auto()
    IF = auto()
    LEFT_PAREN = auto()
    RIGHT_PAREN = auto()
    LEFT_CURLY_BR = auto()
    RIGHT_CURLY_BR = auto()
    LEFT_SQR_BR = auto()
    RIGHT_SQR_BR = auto()
    COMMA = auto()
    DOT = auto()
